export const env = {
  RESEND_API_KEY: process.env.RESEND_API_KEY ?? "",
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID ?? "",
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID ?? "",
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY ?? "",
  R2_BUCKET_NAME: process.env.R2_BUCKET_NAME ?? "",
  R2_PUBLIC_URL: process.env.R2_PUBLIC_URL ?? "",
  MAGAZINE_API_URL: process.env.MAGAZINE_API_URL ?? "",
  MAGAZINE_API_KEY: process.env.MAGAZINE_API_KEY ?? "",
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID ?? "",
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET ?? "",
  SPOTIFY_PLAYLIST_ID: process.env.SPOTIFY_PLAYLIST_ID ?? "",
  SPOTIFY_REFRESH_TOKEN: process.env.SPOTIFY_REFRESH_TOKEN ?? "",
  SPOTIFY_SP_DC: process.env.SPOTIFY_SP_DC ?? "",
} as const;
